data:
  images_train_folder: data/st_images
  train_dataset: data/ViTextVQA_train.json
  images_val_folder: data/st_images
  val_dataset: data/ViTextVQA_dev.json
  test_dataset: data/ViTextVQA_test.json
  num_worker: 2

tokenizer:
  padding: max_length
  max_input_length: 32
  max_target_length: 32
  truncation: True
  return_token_type_ids: True
  return_attention_mask: True

text_embedding:
  text_encoder: bert-base-multilingual-cased
  remove_accents_rate: 0
  use_word_seg: False

vision_embedding:
  image_encoder: microsoft/git-base
  already_extracted: False
  feature_path: data/feature_VIT

generator_args:
  max_length: 35
  min_length: 1
  num_beams: 4
  length_penalty: 1.5
  no_repeat_ngram_size: 3
  early_stopping: True

model:
  type_model: git  # Custom name for the multimodal model

train:
  output_dir: checkpoint
  cuda_device: cuda:0
  precision: float32
  seed: 12345
  num_train_epochs: 100
  patience: 5
  learning_rate: 1.0e-4
  weight_decay: 0.0
  metric_for_best_model: cider
  per_device_train_batch_size: 8
  per_device_valid_batch_size: 8

infer:
  with_answer: True
  images_test_folder: data/all_img_full
  test_dataset: data/test.json
  per_device_eval_batch_size: 32