data:
  images_train_folder: data/st_images
  train_dataset: data/train.json
  images_val_folder: data/st_images
  val_dataset: data/dev.json
  test_dataset: data/test.json
  num_worker: 0

tokenizer:
  padding: max_length
  max_input_length: 100
  max_target_length: 24
  truncation: True
  return_token_type_ids: True
  return_attention_mask: True

text_embedding:
  text_encoder: VietAI/vit5-base
  remove_accents_rate: 0
  use_word_seg: False
  use_lora: lora_all

vision_embedding:
  image_encoder: Salesforce/blip2-opt-2.7b
  already_extracted: False
  feature_path: data/feature_VIT

ocr_embedding:
  sort_type: score # score or top-left bottom-right
  path_ocr: data/ocr_feature
  threshold: 0.3
  remove_accents_rate: 0
  use_word_seg: False
  max_scene_text: 32  ##if not use, set 0
  d_det: 256
  d_rec: 256
  max_2d_position_embeddings: 1024

obj_embedding:
  path_obj: data/obj_feature
  use_attr: False # the  max_input_length should be set 300 if True else 100
  max_bbox: 32  ##if not use, set 0
  d_obj: 2048
  d_grid: 1024


generator_args:
  max_length: 20
  min_length: 1
  num_beams: 4
  length_penalty: 1.5
  no_repeat_ngram_size: 3
  early_stopping: True

model:
  type_model: viblip_promax  # Custom name for the multimodal model

train:
  output_dir: checkpoint
  cuda_device: cuda:0
  precision: float32
  seed: 12345
  num_train_epochs: 100
  patience: 5
  learning_rate: 1.0e-3
  weight_decay: 0.0
  metric_for_best_model: cider
  per_device_train_batch_size: 32
  per_device_valid_batch_size: 32

infer:
  with_answer: True
  images_test_folder: data/st_images
  test_dataset: data/test.json
  per_device_eval_batch_size: 64